### ISSUE TITLE
Export features data into a WCON file

### ISSUE THREAD

**Issue by ver228** [ver228/tierpsy-tracker#15]
We want a format that is compatible accross multiple labs. The modified version of JSON, the WCOM from [tracker commons](https://github.com/openworm/tracker-commons) is the way to go. 

The best step for this in the pipe line is the features file since it contains the most compatible output. I still haven't decided the best way to go and I need to do several tests in terms of file size and processing speed, but it is a feature that is likely to be integrated.

**Comment by MichaelCurrie** [comment]
If you want to know performance of the Python version, [I calculated it here](https://github.com/openworm/tracker-commons/issues/55):

>**Python performance summary**

>File used for test: `tracker-commons/tests/from_schafer_lab.wcon`
>Size: 59.3 MB (4641 frames, ~ 250 points x and 250 points y per frame)
>Zipped size: 5.57 MB

>| Instruction  | Time (seconds)  |  `jsonschema.validate` used? | Cores used |
| ------------- | ------------- | ------------- | ------- |
| WCONWorms.load_from_file  | 1.00  | No | 1 |
| WCONWorms.load_from_file  | 74.29  | Yes | 1 |
| WCONWorms.save_to_file  | 5.38  | n/a | 1 |

**Comment by ver228** [comment]
Hey, thanks. If I am honest it worries me the file size. For the single worm it will be pretty straight forward, but I have some videos on the multiworm case that are a few gigabites long on hdf5 using internal gzip compression. I do not think I can even handdle it in memory. The WCON support dividing data into separate files right? 
Anyway I need to understand better the format/code, and make some test. I'll try to work on this on it the next few days.

**Comment by MichaelCurrie** [comment]
Yes the WCON format supports separate into files, and loading and saving from zipped files (using the universal [DEFLATE](https://en.wikipedia.org/wiki/DEFLATE) algorithm).  With this compression the file size compared with a binary format will be very similar or even smaller.

**Comment by ver228** [comment]
This is implemented.
